### ISSUE TITLE
Tons of warnings with node 6.X

### ISSUE THREAD

**Issue by Klathmon** [mscdex/node-xxhash#11]
Just a heads up, this package is throwing TONS of pretty massive stack traces in node 6.X (i've specifically tried with 6.1 and 6.2 with the same results).

At the end of each is the following:

    (node) v8::ObjectTemplate::Set() with non-primitive values is deprecated
    (node) and will stop working in the next major release.

One of the full stack traces if it helps is [here](https://gist.github.com/Klathmon/d88658f34e43903f2bb9154d40431608).

**Comment by oebspm** [comment]
The same here.

**Comment by aunz** [comment]
I have seen similar issues in other repos, it looks like this can be fixed by upgrading the dependency nan to 2.4.0 (currently is "^2.0.9"), see https://github.com/nodejs/nan/commit/a90951e9ea70fa1b3836af4b925322919159100e. I wish I could help but I don't know much about C++

**Comment by Termina1** [comment]
@aunz the problem in the module itself, has to use newer nan api, fixed this here https://github.com/mscdex/node-xxhash/pull/12
