### ISSUE TITLE
Lot of warning on Node 10

### ISSUE THREAD

**Issue by HRK44** [mscdex/node-xxhash#23]
I think it's related to #11 (for node 6)

``
In file included from ../../nan/nan_new.h:189:0,
                 from ../../nan/nan.h:222,
                 from ../src/common.hpp:6,
                 from ../src/hash_32.hpp:4,
                 from ../src/hash.cc:3:
../../nan/nan_implementation_12_inl.h: In static member function ‘static Nan::imp::FactoryBase<v8::StringObject>::return_t Nan::imp::Factory<v8::StringObject>::New(v8::Local<v8::String>)’:
../../nan/nan_implementation_12_inl.h:340:37: warning: ‘static v8::Local<v8::Value> v8::StringObject::New(v8::Local<v8::String>)’ is deprecated: Use Isolate* version [-Wdeprecated-declarations]
   return v8::StringObject::New(value).As<v8::StringObject>();
                                     ^
In file included from /home/olen/.node-gyp/10.13.0/include/node/v8.h:26:0,
                 from /home/olen/.node-gyp/10.13.0/include/node/node.h:63,
                 from ../src/hash.cc:1:
/home/olen/.node-gyp/10.13.0/include/node/v8.h:5053:37: note: declared here
                 static Local<Value> New(Local<String> value));
                                     ^
/home/olen/.node-gyp/10.13.0/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../src/common.hpp:6:0,
                 from ../src/hash_32.hpp:4,
                 from ../src/hash.cc:3:
../../nan/nan.h: In constructor ‘Nan::Utf8String::Utf8String(v8::Local<v8::Value>)’:
../../nan/nan.h:1066:53: warning: ‘v8::Local<v8::String> v8::Value::ToString() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
       v8::Local<v8::String> string = from->ToString();
                                                     ^
In file included from /home/olen/.node-gyp/10.13.0/include/node/node.h:63:0,
                 from ../src/hash.cc:1:
/home/olen/.node-gyp/10.13.0/include/node/v8.h:10040:15: note: declared here
 Local<String> Value::ToString() const {
               ^~~~~
In file included from ../src/common.hpp:6:0,
                 from ../src/hash_32.hpp:4,
                 from ../src/hash.cc:3:
../../nan/nan.h:1080:74: warning: ‘int v8::String::WriteUtf8(char*, int, int*, int) const’ is deprecated: Use Isolate* version [-Wdeprecated-declarations]
         length_ = string->WriteUtf8(str_, static_cast<int>(len), 0, flags);
                                                                          ^
In file included from /home/olen/.node-gyp/10.13.0/include/node/v8.h:26:0,
                 from /home/olen/.node-gyp/10.13.0/include/node/node.h:63,
                 from ../src/hash.cc:1:
/home/olen/.node-gyp/10.13.0/include/node/v8.h:2659:21: note: declared here
                 int WriteUtf8(char* buffer, int length = -1,
                     ^
/home/olen/.node-gyp/10.13.0/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../src/hash.cc:3:0:
../src/hash_32.hpp: In static member function ‘static uint32_t Hash32::convert_seed(v8::Local<v8::Value>)’:
../src/hash_32.hpp:57:38: warning: ‘uint32_t v8::Value::Uint32Value() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
         return seed_val->Uint32Value();
                                      ^
In file included from /home/olen/.node-gyp/10.13.0/include/node/v8.h:26:0,
                 from /home/olen/.node-gyp/10.13.0/include/node/node.h:63,
                 from ../src/hash.cc:1:
/home/olen/.node-gyp/10.13.0/include/node/v8.h:2477:47: note: declared here
   V8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
                                               ^
/home/olen/.node-gyp/10.13.0/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../src/hash.cc:4:0:
../src/hash_64.hpp: In static member function ‘static uint64_t Hash64::convert_seed(v8::Local<v8::Value>)’:
../src/hash_64.hpp:57:38: warning: ‘uint32_t v8::Value::Uint32Value() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
         return seed_val->Uint32Value();
                                      ^
In file included from /home/olen/.node-gyp/10.13.0/include/node/v8.h:26:0,
                 from /home/olen/.node-gyp/10.13.0/include/node/node.h:63,
                 from ../src/hash.cc:1:
/home/olen/.node-gyp/10.13.0/include/node/v8.h:2477:47: note: declared here
   V8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
                                               ^
/home/olen/.node-gyp/10.13.0/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
  CC(target) Release/obj.target/hash/deps/xxhash/xxhash.o
  SOLINK_MODULE(target) Release/obj.target/hash.node
  COPY Release/hash.node``

**Comment by gamelaster** [comment]
Hi, I'm building xxhash on latest Node and I don't have this warnings

**Comment by mscdex** [comment]
These should be resolved in master now.
