### ISSUE TITLE
Error in Electron: relative module was not found

### ISSUE THREAD

**Issue by aleksey-hoffman** [mscdex/node-xxhash#34]
Hi there. I'm getting the following error after adding `xxhash` to an Electron app created with [vue-cli-plugin-electron-builder](https://github.com/nklayman/vue-cli-plugin-electron-builder):
```
This relative module was not found:
../build/Release/hash in ./node_modules/xxhash/lib/xxhash.js
```
And here's the `yarn add xxhash` command log:
```
yarn install v1.22.4
[1/4] Resolving packages...
success Already up-to-date.
$ electron-builder install-app-deps
  • electron-builder  version=21.2.0
  • rebuilding native dependencies  dependencies=diskusage@1.1.3, xxhash@0.3.0 platform=win32 arch=x64
  • rebuilding native dependency  name=diskusage version=1.1.3
  • rebuilding native dependency  name=xxhash version=0.3.0
Done in 11.46s.
```

Can someone suggest a solution for this?

**Environment:** 
- Windows 10 x64
- Electron: v8.2.0 (Node v12.13.0)

**Comment by mscdex** [comment]
You're probably better off asking on the electron project issue tracker.

**Comment by aleksey-hoffman** [comment]
@mscdex yeah, I suppose so, sorry for bothering with this, I thought the module was causing the error, but perhaps the `electron-builder` might be the source of the problem here.
